<a href="https://colab.research.google.com/github/NANDANAV557/Datascience/blob/main/prgm_1to5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
array_from_list = np.array([1,2,3,4,5])
print("array from list:",array_from_list)

array_with_range = np.arange(10)
print("array with range:",array_with_range)

zeros_array = np.zeros((3,3))
print("array of zeros:\n",zeros_array)

ones_array = np.ones((2,5))
print("array of ones:\n",ones_array)

array from list: [1 2 3 4 5]
array with range: [0 1 2 3 4 5 6 7 8 9]
array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

add_result = np.add(a,b)
print("addition result:",add_result)

sub_result = np.subtract(a,b)
print("subtraction result:",sub_result)

mul_result = np.multiply(a,b)
print("multiplication result:",mul_result)

div_result = np.divide(a,b)
print("division result:",div_result)

addition result: [5 7 9]
subtraction result: [-3 -3 -3]
multiplication result: [ 4 10 18]
division result: [0.25 0.4  0.5 ]


In [8]:
array = np.arange(12)
print("orginal array:",array)

array_reshaped = np.reshape(array,(3,4))
print("reshaped array:\n",array_reshaped)

reshaped_array_3D = np.reshape(array,(2,3,2))
print("3D reshaped array:\n",reshaped_array_3D)

orginal array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3D reshaped array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [10]:
array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:\n",array_2d)

element = array_2d[1,2]
print("element at (1,2):",element)

subarray = array_2d[1:3,0:2]
print("sliced subarray:\n",subarray)

column = array_2d[:,1]
print("column 1:",column)

2D array:
 [[1 2 3]
 [4 5 6]]
element at (1,2): 6
sliced subarray:
 [[4 5]]
column 1: [2 5]


In [11]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("original array:",array)

mean = np.mean(array)
print("mean:",mean)

median = np.median(array)
print("median:",median)

std_dev = np.std(array)
print("standard deviation:",std_dev)

min_val = np.min(array)
print("minimum value:",min_val)

max_val = np.max(array)
print("maximum value:",max_val)

original array: [ 1  2  3  4  5  6  7  8  9 10]
mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
minimum value: 1
maximum value: 10
